export const AUTH_SET_LOADING = 'SIGIN_SET_LOADING';
export const AUTH_UNSET_LOADING = 'SIGIN_UNSET_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_RESET = 'AUTH_RESET';
export const GET_COUPON = 'GET_COUPON';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';

export const SIGIN_USER = 'SIGIN_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_RESET_FORM = 'SIGNUP_RESET_FORM';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SIGNUP_USER = 'SIGNUP_USER';
export const ON_SUBSCRIBE = 'ON_SUBSCRIBE';

export const AUTH_INFO_SET = 'AUTH_INFO_SET';
export const SIGNUP_PAYMENT_STEP = 'SIGNUP_PAYMENT_STEP';
export const SEND_COUPON = 'SEND_COUPON';

export const SET_SETTINGS = 'SET_SETTINGS';
export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_STATIC_PAGES = 'GET_STATIC_PAGES';
export const SET_STATIC = 'SET_STATIC';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const GET_INTROS = 'GET_INTROS';
export const SET_INTROS = 'SET_INTROS';
export const ON_MESSAGE = 'ON_MESSAGE';
export const MESSAGES_CLEAR = 'MESSAGES_CLEAR';
export const GET_MAGICIANS = 'GET_MAGICIANS';
export const SET_MAGICIANS = 'SET_MAGICIANS';

export const GET_VIDEOS = 'GET_VIDEOS';
export const SET_SEARCHED_VIDEOS = 'SET_SEARCHED_VIDEOS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS';

/* Media actions */
export const GET_TUTORIALS_INTRO = 'GET_TUTORIALS_INTRO';
export const SET_TUTORIALS_INTRO = 'SET_TUTORIALS_INTRO';
export const CLEAR_TUTORIALS_INTRO = 'CLEAR_TUTORIALS_INTRO';
export const GET_CARD_VIDEO = 'GET_CARD_VIDEO';
export const SET_CARD_VIDEO = 'SET_CARD_VIDEO';
export const CLEAR_CARD_VIDEO = 'CLEAR_CARD_VIDEO';
export const GET_MAGICIAN_TUTORIALS = 'GET_MAGICIAN_TUTORIALS';
export const SET_MAGICIAN_VIDEOS = 'SET_MAGICIAN_VIDEOS';
export const CLEAR_MAGICIAN_VIDEOS = 'CLEAR_MAGICIAN_VIDEOS';
export const SET_CURRENT_INTRO = 'SET_CURRENT_INTRO';
export const GET_MAGICIAN_VIDEOS = 'GET_MAGICIAN_VIDEOS';
export const SET_MAGICIAN_CATEGORIES_VIDEOS = 'SET_MAGICIAN_CATEGORIES_VIDEOS';
export const GET_VIDEO_REVIEWS = 'GET_VIDEO_REVIEWS';
export const SET_VIDEO_REVIEWS = 'SET_VIDEO_REVIEWS';
export const SET_VIDEO_REVIEW = 'SET_VIDEO_REVIEW';
export const CREATE_VIDEO_REVIEW = 'CREATE_VIDEO_REVIEW';
export const GET_PAGE_VIDEO = 'GET_PAGE_VIDEO';
export const SET_PAGE_VIDEO = 'SET_PAGE_VIDEO';
export const CLEAR_PAGE_VIDEO = 'CLEAR_PAGE_VIDEO';

/* User actions */
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const SET_FAVOTIRES_VIDEOS = 'SET_FAVOTIRES_VIDEOS';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const TRACK_VIDEO = 'TRACK_VIDEO';
export const GET_ACTIVE_PROFILE = 'GET_ACTIVE_PROFILE';
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';
export const LIKE_VIDEO = 'LIKE_VIDEO';
export const SET_CARD_LIKES = 'SET_CARD_LIKES';
export const DISLIKE_VIDEO = 'DISLIKE_VIDEO';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const GET_SUB_PROFILE = 'GET_SUB_PROFILE';
export const PROFILE_DELETE = 'PROFILE_DELETE';
export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
export const ACCOUNT_DELETE = 'ACCOUNT_DELETE';
